### ISSUE TITLE
Potential collaboration

### ISSUE THREAD

**Issue by open-dynaMIX** [husudosu/mpv-remote-app#1]
Hey @husudosu

Very nice project! I'm the author of [simple-mpv-webui](https://github.com/open-dynaMIX/simple-mpv-webui), which does pretty much the same, but without a native app.
So I was thinking, it would be great if we could share a common (or at least compatible) backend. This would give users the option of using the app, the web page or a [custom frontend](https://github.com/open-dynaMIX/simple-mpv-webui#static_dir) as they wish, with just one single MPV plugin. Here you can find the [documentation of the API](https://github.com/open-dynaMIX/simple-mpv-webui#endpoints) provided by simple-mpv-webui. This can be extended/adapted, if you need any calls not covered yet.

So, please let me know, if you're up for some kind of collaboration.

All the best!

**Comment by husudosu** [comment]
Yeah, sure why not. Someone on Reddit on r/mpv told about your project yesterday. Took a look and it would have made my development much easier, by using that backend. :) 
My backend also supports mediastatus storing, on a local database (Sqlite). Is there something similar available for your project? 
It's important for me, to store watched/unfinished media status on backend.

**Comment by husudosu** [comment]
Hi!
Yeah I heard about your project, yesterday on Reddit r/mpv someone told me about it. It would have made my development much easier using your API. So of course im up to collaboration.
If I see correctly, your backend not supports media status like mine do (storing playback time and the file finished also store that on backend SQLITE database on my case) It's important for me, I consume lot media, so I want keep track of them preferably on backend. Is it implementable for your Lua backend?

**Comment by open-dynaMIX** [comment]
Awesome!

> If I see correctly, your backend not supports media status like mine do (storing playback time and the file finished also store that on backend SQLITE database on my case) It's important for me, I consume lot media, so I want keep track of them preferably on backend Is it implementable for your Lua backend?

My backend doesn't store anything. It's just an API to control MPV, nothing less, nothing more. The only state it consumes comes directly from MPV. For picking up playback where I left, I use the built-in `watch-later` functionality from MPV.

To be honest, I don't really understand, why a remote control should keep a record of all played files. IMO this functionality is not really expected and it wouldn't work for me, as I only run the webui if I intend to remotely control MPV. I don't want to expose my media player controls on the company network for example. But for your use case you'd still want to keep track of the files played in such a scenario, right?

So I see two possible solutions for this:

 1. Store it on the client (if you want to use my API, but still keep this functionality)
 2. Use a separate script for keeping track of played media. This plugin could write played files into a DB and/or into one or several playlists for example. [Here I found one](https://github.com/hacel/recent) that writes it in a log file and provides an interactive menu

Another difference I saw is this: While I provide a `loadfile` endpoint, I don't expose the whole file system and for security reasons, I want to keep it that way. I could think of a config option for the backend to expose certain directories. So you could for example set it to `/home/user/music;/home/user/movies` in order to expose those directories. But by default, clients should not be able to query any files and for sure not the whole file system.

So, if you're still interested, let me know what changes you think will be needed, to the API.

**Comment by husudosu** [comment]
Thanks for the response!
Lot ideas came from Kodi & Yatse remote for android. Kodi stores everything on local database (I know it's a media center and MPV is just a player). So I thought, will store collections on backend DB. It's easier when guests come over, and I don't have configure my collections for them manually on their devices. Probably my watchlist handling is not the best on a backend, becasue it's a private thing, it should be stored on Application frontend (other designing issue) :) . 
I get your concerns  about exposing local filesystem and I agree with it. My app also supports collection handling. I'm gonna change this behaviour.
I'll create other branch and start work on frontend by using your API, next week.

**Comment by open-dynaMIX** [comment]
Awesome! Let me know if I can assist you in any way.

**Comment by SonaliBendre** [comment]
simple-web-ui doesn't work in Windows for anyone but mpv-remote is cross platform @open-dynaMIX 

I hope @open-dynaMIX respond to @open-dynaMIX 's request in email or via chat otherwise its disrespectful if he didn't comment in this issue for long time. Actually Github issue is bad for discussion, it should be like discord
