### ISSUE TITLE
File browser not working

### ISSUE THREAD

**Issue by stax76** [husudosu/mpv-remote-app#12]
I have everything now working, except for the file browser, it shows `Loading...` forever. Any ideas what could be wrong?

```
uselocaldb=1
webport=8000
webportrangeend=8004
unsafefilebrowsing=1
verbose=0
osd-messages=0
filebrowserpaths="'E:\';'D:\Music'"
```

**Comment by husudosu** [comment]
If unsafefilebrowsing is enabled, you don't have to provide filebrowserpaths.  The mpv-remote-node documentation not says that clearly, sorry. 

The filebrowser should load both ways (so your configuration should work). Maybe try to clear app data and try again. 
Look for terminal output of mpv.net if there is some exceptions.

**Comment by stax76** [comment]
Sorry, I forgot to post that it works now, probably needed to reboot.
