### ISSUE TITLE
1.0.8 icon's off, I think

### ISSUE THREAD

**Issue by plissken1138** [husudosu/mpv-remote-app#8]
Looks like stock android icon to me.

![nooooo](https://i.imgur.com/aakYRi8.png)

Huawei P9, android 7

**Comment by husudosu** [comment]
Yeah it's the stock Android icon. I've created an icon for my app using Android studio, but it seems something went wrong. Maybe older Android handles app icons differently. On my phone running Android 12 works fine. Thanks for letting me know, I'll fix this issue.

**Comment by husudosu** [comment]
I've released 1.0.9 with the fix. Let me know if it's working for you.
If you've installed the app via IzzyOnDroid 1.0.9 gonna available around 20:00 (GMT+2 timezone)
[Or if you have installed from the Github releases here you can download the fixed version.](https://github.com/husudosu/mpv-remote-app/releases/tag/1.0.9)

**Comment by husudosu** [comment]
Oh, something is not right then, I'll remove the release. I'll investigate it on the weekend, until then downgrade to 1.0.8 or 1.0.7. Sorry.

**Comment by azizLIGHT** [comment]
On Android 10, icon looks OK for 1.0.8
![Screenshot_20220712-220110](https://user-images.githubusercontent.com/8013867/178635189-5bcffdc4-1fbe-4326-bcac-868f1784a35a.png)

**Comment by husudosu** [comment]
Yeah, the issue only exists on Android 7, it's being fixed. I want to implement some new functionality and bug fixes before relasing a new version.

**Comment by plissken1138** [comment]
Since the icon is fixed and 1.0.9 is working OK on Android 7, I'm closing this.
